service: lambda-code-runner

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1  # or your AWS region

functions:
  runCode:
    handler: index.handler  # ✅ index.js must export a function named "handler"
    events:
      - http:
          path: run
          method: post

package:
  individually: true

custom:
  esbuild:
    bundle: true         # ✅ Bundle all code into one file
    minify: true         # ✅ Compress the code
    target: node18       # ✅ Match your Lambda runtime
    platform: node
    exclude:
      - aws-sdk